proxies:
  - name: SERVER JP
    server: poe.garena.com
    port: 443
    type: vless
    uuid: 0c39010d-4265-475f-9e4f-db013e3656fa
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: jp1.masfen.xyz
    network: ws
    ws-opts: 
      path: /vless-ws
      headers: 
        Host: jp1.masfen.xyz
    udp: true
  - name: AXIS GAME
    server: poe.garena.com
    port: 80
    type: vless
    uuid: b2c3bf93-5349-4d5f-bfd7-3960e86d60ff
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: poe.garena.com
    network: ws
    ws-opts: 
      path: /vless
      headers: 
        Host: id.vless.sbs
    udp: true
  - name: VLESS TELE
    server: ovo.id
    port: 443
    type: vmess
    uuid: dee4fce4-1a57-468e-954e-24c8901942e3
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: 9391.vless.sbs
    network: ws
    ws-opts: 
      path: /vmess-ws
      headers: 
        Host: 9391.vless.sbs
    udp: true
  - name: JP TELE
    server: embed.tawk.to
    port: 80
    type: vless
    uuid: 97de2e74-0c83-402a-a472-fe6a7018f4af
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: embed.tawk.to
    network: ws
    ws-opts: 
      path: /vless-ws
      headers: 
        Host: jp1.globalnet.my.id
    udp: true
