proxies:
  - name: AXIS GAME CA
    server: 104.18.36.235
    port: 80
    type: vless
    uuid: 77fed22f-954a-4125-8eb0-e51717daf236
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: vless-ovh-ca01.globalssh.xyz
    network: ws
    ws-opts:
      path: /vless-ws
      headers:
        Host: vless-ovh-ca01.globalssh.xyz
    udp: true
  - name: AXIS OPOK CA
    server: ovo.id
    port: 80
    type: vless
    uuid: 77fed22f-954a-4125-8eb0-e51717daf236
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: vless-ovh-ca01.globalssh.xyz
    network: ws
    ws-opts:
      path: /vless-ws
      headers:
        Host: vless-ovh-ca01.globalssh.xyz
    udp: true
  - name: AXIS OPOK2 CA
    server: arjuna.axis.co.id
    port: 80
    type: vless
    uuid: 77fed22f-954a-4125-8eb0-e51717daf236
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: vless-ovh-ca01.globalssh.xyz
    network: ws
    ws-opts:
      path: /vless-ws
      headers:
        Host: vless-ovh-ca01.globalssh.xyz
    udp: true
  - name: SG PREMIUM
    server: poe.garena.com
    port: 80
    type: vless
    uuid: 5627a4d6-cb3b-4d7d-bd56-e5687010cc9c
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: sg01.ipxray.xyz
    network: ws
    ws-opts: 
      path: /vless-ws
      headers: 
        Host: sg01.ipxray.xyz
    udp: true
