proxies:
  - name: SERVER SG
    server: poe.garena.com
    port: 80
    type: vless
    uuid: 61a5affb-145d-427a-bf27-5c248eee11d4
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: vless-sg01.globalssh.xyz
    network: ws
    ws-opts: 
      path: /vless-ws
      headers: 
        Host: vless-sg01.globalssh.xyz
    udp: true
  - name: AXIS OPOK1
    server: ovo.id
    port: 80
    type: vless
    uuid: 61a5affb-145d-427a-bf27-5c248eee11d4
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: vless-sg01.globalssh.xyz
    network: ws
    ws-opts: 
      path: /vless-ws
      headers: 
        Host: vless-sg01.globalssh.xyz
    udp: true
  - name: AXIS OPOK2
    server: arjuna.axis.co.id
    port: 80
    type: vless
    uuid: 61a5affb-145d-427a-bf27-5c248eee11d4
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: vless-sg01.globalssh.xyz
    network: ws
    ws-opts: 
      path: /vless-ws
      headers: 
        Host: vless-sg01.globalssh.xyz
    udp: true
  - name: PREMIUM DE
    server: poe.garena.com
    port: 80
    type: vless
    uuid: da56a5cd-0709-4840-8b53-7b0fe5baf2f5
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: vless-adv-de01.globalssh.xyz
    network: ws
    ws-opts: 
      path: /vless-ws
      headers: 
        Host: vless-adv-de01.globalssh.xyz
    udp: true
  - name: FREE SG
    server: poe.garena.com
    port: 80
    type: vless
    uuid: 188eb770-1e87-11ef-a9d4-1239d0255272
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: sg3.socifiles.com
    network: ws
    ws-opts: 
      path: /vlws
      headers: 
        Host: sg3.socifiles.com
    udp: true
