proxies:
  - name: AXIS SG
    server: poe.garena.com
    port: 80
    type: vless
    uuid: d1c64182-ec37-41c0-bf61-dd39d428054a
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: null
    network: ws
    ws-opts: 
      path: /vless
      headers: 
        Host: aray.josvpn.me
    udp: true
  - name: OPOK
    server: ovo.id
    port: 80
    type: vless
    uuid: d1c64182-ec37-41c0-bf61-dd39d428054a
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: null
    network: ws
    ws-opts: 
      path: /vless
      headers: 
        Host: aray.josvpn.me
    udp: true
  - name: JEPANG
    server: poe.garena.com
    port: 80
    type: vless
    uuid: c39a3a3e-b234-48d4-92af-cee20efabbe8
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: poe.garena.com
    network: ws
    ws-opts: 
      path: /vless
      headers: 
        Host: xjp.josvpn.me
    udp: true
  - name: SINGAPORE
    server: poe.garena.com
    port: 80
    type: vmess
    uuid: 5c63ab9d-c6b0-447e-a114-009b6a072f10
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    servername: 
    network: ws
    ws-opts: 
      path: /vmess
      headers: 
        Host: aray.josvpn.me
    udp: true
  - name: FREE SG
    server: poe.garena.com
    port: 80
    type: vless
    uuid: 0ab3beaa-f4e6-4c72-8eed-fa3711b011f8
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: aray.josvpn.me
    network: ws
    ws-opts: 
      path: /vless
      headers: 
        Host: aray.josvpn.me
    udp: true
  - name: CLOUDFRONT
    server: 18.161.49.45
    port: 80
    type: vless
    uuid: 0ab3beaa-f4e6-4c72-8eed-fa3711b011f8
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: aray.josvpn.me
    network: ws
    ws-opts: 
      path: /vless
      headers: 
        Host: j14331x3c34771zm51.speedup.mobi
    udp: true
  - name: CLOUDFRONT 2
    server: 18.161.49.45
    port: 80
    type: vless
    uuid: d1c64182-ec37-41c0-bf61-dd39d428054a
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: null
    network: ws
    ws-opts: 
      path: /vless
      headers: 
        Host: j14331x3c34771zm51.speedup.mobi
    udp: true
  - name: CLOUDFRONT 3
    server: 18.161.49.45
    port: 80
    type: vless
    uuid: d1c64182-ec37-41c0-bf61-dd39d428054a
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: null
    network: ws
    ws-opts: 
      path: /vless
      headers: 
        Host: 213o1m08591e72t7a3.speedup.mobi
    udp: true
  - name: SINGAPORE
    server: poe.garena.com
    port: 80
    type: vless
    uuid: a0539611-03f8-4289-80ec-f7203d8fc1ff
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: aray.josvpn.me
    network: ws
    ws-opts: 
      path: /vless
      headers: 
        Host: aray.josvpn.me
    udp: true
  - name: SG VULTR
    server: poe.garena.com
    port: 443
    type: vless
    uuid: f9021b31-e8bd-4b4d-a1d3-c9b0c1476c44
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: free.putrivpn.biz.id
    network: ws
    ws-opts: 
      path: /vlesscf
      headers: 
        Host: free.putrivpn.biz.id
    udp: true
  - name: GERMAN
    server: poe.garena.com
    port: 443
    type: vless
    uuid: 8651201d-4a01-4882-9b6e-2cc3ef595fc3
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: vless-adv-de01.globalssh.xyz
    network: ws
    ws-opts: 
      path: /vless-ws
      headers: 
        Host: vless-adv-de01.globalssh.xyz
    udp: true
