proxies:
  - name: PREMIUM
    server: poe.garena.com
    port: 443
    type: vmess
    uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: to.tilebani.com
    network: ws
    ws-opts: 
      path: /linkvws
      headers: 
        Host: to.tilebani.com
    udp: true
  - name: TRIAL
    server: ovo.id
    port: 443/
    type: vless
    uuid: 18e52006-2a99-42e4-8fd3-08df8c5a60e1
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: sg01.ipxray.xyz
    network: ws
    ws-opts: 
      path: /vless-ws
      headers: 
        Host: sg01.ipxray.xyz
    udp: true
