proxies:
  - name: AXIS GAME CA
    server: 104.18.36.235
    port: 80
    type: vless
    uuid: 77fed22f-954a-4125-8eb0-e51717daf236
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: vless-ovh-ca01.globalssh.xyz
    network: ws
    ws-opts:
      path: /vless-ws
      headers:
        Host: vless-ovh-ca01.globalssh.xyz
    udp: true
  - name: AXIS OPOK CA
    server: ovo.id
    port: 80
    type: vless
    uuid: 77fed22f-954a-4125-8eb0-e51717daf236
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: vless-ovh-ca01.globalssh.xyz
    network: ws
    ws-opts:
      path: /vless-ws
      headers:
        Host: vless-ovh-ca01.globalssh.xyz
    udp: true
  - name: AXIS OPOK2 CA
    server: arjuna.axis.co.id
    port: 80
    type: vless
    uuid: 77fed22f-954a-4125-8eb0-e51717daf236
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: vless-ovh-ca01.globalssh.xyz
    network: ws
    ws-opts:
      path: /vless-ws
      headers:
        Host: vless-ovh-ca01.globalssh.xyz
    udp: true
  - name: AXIS SG
    server: ovo.id
    port: 80
    type: vmess
    uuid: eb4d2130-1e5a-11ef-be1c-1239d0255272
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: sg3.socifiles.com
    network: ws
    ws-opts:
      path: /vmws
      headers:
        Host: sg3.socifiles.com
    udp: true
