proxies:
  - name: AXIS GAMING
    server: 104.18.36.235
    port: 80
    type: vless
    uuid: 77fed22f-954a-4125-8eb0-e51717daf236
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: vless-ovh-ca01.globalssh.xyz
    network: ws
    ws-opts:
      path: /vless-ws
      headers:
        Host: vless-ovh-ca01.globalssh.xyz
    udp: true
 - name: AXIS OPOK
    server: ovo.id
    port: 80
    type: vless
    uuid: 77fed22f-954a-4125-8eb0-e51717daf236
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: vless-ovh-ca01.globalssh.xyz
    network: ws
    ws-opts:
      path: /vless-ws
      headers:
        Host: vless-ovh-ca01.globalssh.xyz
    udp: true    
 - name: AXIS TRIAL
    server: sg01.ipv2ray.xyz
    port: 443
    type: vmess
    uuid: 92bab1a1-adc8-41ab-83d4-503d7c76d028
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: sg01.ipv2ray.xyz
    network: ws
    ws-opts:
      path: /vmess-ws
      headers:
        Host: poe.garena.com
    udp: true
