proxies:
  - name: PREMIUM
    server: poe.garena.com
    port: 443
    type: vmess
    uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: to.tilebani.com
    network: ws
    ws-opts: 
      path: /linkvws
      headers: 
        Host: to.tilebani.com
    udp: true
  - name: TRIAL SG
    server: ovo.id
    port: 80/
    type: vless
    uuid: 86fe64be-25b2-4ca4-ada0-a27c49a4ff81
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: ovo.id
    network: ws
    ws-opts: 
      path: /vless-ws#TRIAL
      headers: 
        Host: sg02.ipxray.xyz
    udp: true
  - name: TRIAL SSH
    server: poe.garena.com
    port: 80/
    type: vless
    uuid: 86fe64be-25b2-4ca4-ada0-a27c49a4ff81
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: ovo.id
    network: ws
    ws-opts: 
      path: /vless-ws#TRIAL
      headers: 
        Host: sg02.ipxray.xyz
    udp: true
